### ISSUE TITLE
when using a Gemfile failing on pod --version

### ISSUE THREAD

**Issue by rymir** [bitrise-io/steps-cocoapods-install#1]
when using a Gemfile to get a specific cocoapods version and setting update cocoapods to false, the script always fails on line https://github.com/bitrise-io/steps-cocoapods-install/blob/81a7d346518dcb8851e86864a396b63ad48bcfe6/step.sh#L20
with
```
* Failed to get current Cocoapods version
```

**Comment by viktorbenei** [comment]
Hi @rymir - thank you for reporting this issue. Can you please share a GitHub repository where we could reproduce this issue?

As you can see it in our CocoaPods sample repo it has exactly the setup you described, and it still does not fail: https://github.com/bitrise-io/sample-apps-ios-cocoapods/tree/master/SampleAppWithCocoapods

You can fork this repository and modify it to reproduce the issue.

For reference this was the `bitrise.yml` of the test:

```
---
format_version: 1.0.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - BITRISE_PROJECT_PATH: "./SampleAppWithCocoapods/SampleAppWithCocoapods.xcworkspace"
    opts:
      is_expand: false
  - BITRISE_SCHEME: SampleAppWithCocoapods
    opts:
      is_expand: false
trigger_map:
- pattern: "*"
  is_pull_request_allowed: true
  workflow: primary
workflows:
  primary:
    steps:
    - git-clone@3.0.0:
        outputs:
        - GIT_CLONE_COMMIT_HASH: 
          opts:
            title: Cloned git commit's commit hash
        - GIT_CLONE_COMMIT_MESSAGE_SUBJECT: 
          opts:
            title: Cloned git commit's message subject
        - GIT_CLONE_COMMIT_MESSAGE_BODY: 
          opts:
            title: Cloned git commit's message body
        - GIT_CLONE_COMMIT_AUTHOR_NAME: 
          opts:
            title: Cloned git commit's author name
        - GIT_CLONE_COMMIT_AUTHOR_EMAIL: 
          opts:
            title: Cloned git commit's author email address
        - GIT_CLONE_COMMIT_COMMITER_NAME: 
          opts:
            title: Cloned git commit's committer name
        - GIT_CLONE_COMMIT_COMMITER_EMAIL: 
          opts:
            title: Cloned git commit's committer email
    - cocoapods-install@1.0.1:
        inputs:
        - is_update_cocoapods: 'false'
    - certificate-and-profile-installer@1.2.0: {}
    - select-xcode-version@2.0.0: {}
    - xcode-test@1.2.0:
        title: 'Xcode: Unit Test'
        inputs:
        - simulator_device: iPad
          opts:
            is_expand: false
    - xcode-archive@1.2.0:
        title: 'Xcode: Create Archive'
        inputs:
        - output_dir: "${BITRISE_DEPLOY_DIR}"
        outputs:
        - BITRISE_IPA_PATH: 
          opts:
            title: The created .ipa file's path
        - BITRISE_DSYM_PATH: 
          opts:
            title: The created .dSYM.zip file's path
    envs: 
```

And in the logs:

```
*Skipping Cocoapods version update*
CocoaPods version: 0.38.2
-> $ cd /Users/vagrant/git
# Run pod install
```

Then proceeds and installs CocoaPods `0.38.0` as specified in the `Gemfile`.

**Comment by rymir** [comment]
I forked the repo and modified the `Gemfile` to get a fixed cocoapods `0.39.0.beta.4` version, have a look at https://github.com/rymir/sample-apps-ios-cocoapods/commit/0fba931feeec15801a5ea88622ff91594bf2e803

The I run it on the following `bitrise.yml` but get `cocoapods 0.38.0`:

```
---
format_version: 1.0.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - BITRISE_PROJECT_PATH: "./SampleAppWithCocoapods/SampleAppWithCocoapods.xcodeproj"
    opts:
      is_expand: false
  - BITRISE_SCHEME: SampleAppWithCocoapods
    opts:
      is_expand: false
trigger_map:
- pattern: "*"
  is_pull_request_allowed: true
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@3.0.2:
        title: Activate App SSH key
        inputs:
        - ssh_key_save_path: "$HOME/.ssh/steplib_ssh_step_id_rsa"
    - git-clone@3.0.0:
        outputs:
        - GIT_CLONE_COMMIT_HASH: 
          opts:
            title: Cloned git commit's commit hash
        - GIT_CLONE_COMMIT_MESSAGE_SUBJECT: 
          opts:
            title: Cloned git commit's message subject
        - GIT_CLONE_COMMIT_MESSAGE_BODY: 
          opts:
            title: Cloned git commit's message body
        - GIT_CLONE_COMMIT_AUTHOR_NAME: 
          opts:
            title: Cloned git commit's author name
        - GIT_CLONE_COMMIT_AUTHOR_EMAIL: 
          opts:
            title: Cloned git commit's author email address
        - GIT_CLONE_COMMIT_COMMITER_NAME: 
          opts:
            title: Cloned git commit's committer name
        - GIT_CLONE_COMMIT_COMMITER_EMAIL: 
          opts:
            title: Cloned git commit's committer email
    - cocoapods-install@1.0.1: {}
    envs: 
```

**Comment by viktorbenei** [comment]
@rymir you also have to call a bundle update locally or delete the Gemfile.lock - bundler uses the versions specified in the Gemfile.lock if it's available

**Comment by rymir** [comment]
if you look at the commit https://github.com/rymir/sample-apps-ios-cocoapods/commit/0fba931feeec15801a5ea88622ff91594bf2e803 I actually deleted the `Gemfile.lock` didn't I?

**Comment by viktorbenei** [comment]
@rymir  Sorry I missed that. I tried with your fork and I got a correct CocoaPods version. Are you sure that you used your forked repo's URL, and not the original one?

Logs:

```
Using cocoapods 0.39.0.beta.4
0:  cocoapods (0.39.0.beta.4) from /usr/local/lib/ruby/gems/2.2.0/specifications/cocoapods-0.39.0.beta.4.gemspec
```

The `Gemfile.lock` was also properly updates:

```
cat SampleAppWithCocoapods/Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    ...
    cocoapods (0.39.0.beta.4)
```

And the `Podfile.lock` :

```
cat SampleAppWithCocoapods/Podfile.lock
PODS:
  - Kiwi (2.3.1)

DEPENDENCIES:
  - Kiwi

SPEC CHECKSUMS:
  Kiwi: f038a6c61f7a9e4d7766bff5717aa3b3fdb75f55

COCOAPODS: 0.39.0.beta.4
```

**Comment by rymir** [comment]
Looks pretty right to me, you running the step locally or on bitrise? I'm build on bitrise, you can have a look here https://www.bitrise.io/build/5ae976e7ca07b10b

**Comment by viktorbenei** [comment]
Tried on my own Mac and on bitrise.io as well.

Just pushed a new `cocoapods-install` version which now prints the installed CococaPods version even if it's installed through a `Gemfile`, and it seems to be correct.

If you update the step to `1.0.2` you'll see two new debug log lines:

```
==> Found 'Gemfile' - using it...

...

==> CocoaPods version:
0.39.0.beta.4
  Preparing
```

`bitrise.yml` content (cleaned it up a bit and removed every other step after the `cocoapods-install` step to make it faster for testing):

```
---
format_version: 1.0.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - BITRISE_PROJECT_PATH: "./SampleAppWithCocoapods/SampleAppWithCocoapods.xcworkspace"
  - BITRISE_SCHEME: SampleAppWithCocoapods
trigger_map:
- pattern: "*"
  is_pull_request_allowed: true
  workflow: primary
workflows:
  primary:
    steps:
    - git-clone@3.0.0:
    - cocoapods-install@1.0.2:
        inputs:
        - is_update_cocoapods: 'false'
    - certificate-and-profile-installer@1.2.0: {}
```

Tested with this exact `bitrise.yml` on both bitrise.io and on my own Mac, both printed the correct `==> CocoaPods version: 0.39.0.beta.4` log.
